### ISSUE TITLE
Add Ctrl-K mapping for command mode

### ISSUE THREAD

**Issue by jgdavey** [tpope/vim-rsi#15]
I use this so much at the command line that I frequently do the same in vim.

Ctrl-K deletes "⇥ from the cursor to the end of the line"

There's probably an elegant way to do this using mappings, but I'm not sure how.

**Comment by jeromedalbert** [comment]
FYI, for anyone interested in a way to do this:

```vim
inoremap <c-k> <c-o>D
cnoremap <c-k> <c-\>e getcmdpos() == 1 ? '' : getcmdline()[:getcmdpos()-2]<CR>
```

(since OS X has very good digraph support, I am OK with overriding `ctrl-k`)
