### ISSUE TITLE
ctrl-y doesn't do anything

### ISSUE THREAD

**Issue by moon-chilled** [tpope/vim-rsi#38]

**Comment by pyluyten** [comment]
yes it should "yank previously inserted text" (vim vanilla binding for C-a).

This way
- this is consitent or at least good mnemonic with readline C-y
- this binding which is shadowed by "C-a beginning of line" revives

**Comment by tpope** [comment]
That's a good point, but I don't really want to shadow the built-in `<C-Y>`, which imho is much more useful than the built-in `<C-A>`.

**Comment by justinmk** [comment]
Updated https://github.com/tpope/vim-rsi/pull/17 , which maps `<c-u>` and `<c-y>` in cmdline-mode only.
