### ISSUE TITLE
Meta mappings interfere with vim's :terminal meta mappings

### ISSUE THREAD

**Issue by knatsakis** [tpope/vim-rsi#46]
Meta mappings inside a vim terminal stop working when vim-rsi is loaded.

Opening a vim terminal (:terminal) and typing Alt+f produces ';2C', Alt+b produces ';2D', etc...

I am using vim version 8.1.0229 and zsh.

**Comment by cwfoo** [comment]
@tpope Is there a way to disable this plugin when using `:terminal`? The terminal (e.g. bash) already comes with its own readline keybindings.

**Comment by tpope** [comment]
You can opt out of meta mappings entirely, but no, there isn't a way to selectively disable `set <M-b>=...` in `:terminal`. For the first time in my life I am jealous of N\*\*\*\*m.

**Comment by lacygoill** [comment]
This patch should fix the issue:
```diff
diff --git a/plugin/rsi.vim b/plugin/rsi.vim
index 8ecf2b3..61ab2b0 100644
--- a/plugin/rsi.vim
+++ b/plugin/rsi.vim
@@ -87,11 +87,16 @@ else
   silent! exe "set <F34>=\<Esc>\<C-?>"
   silent! exe "set <F35>=\<Esc>\<C-H>"
   noremap!        <F29> <S-Left>
+  tnoremap        <F29> <Esc>b
   noremap!        <F30> <S-Right>
+  tnoremap        <F30> <Esc>f
   noremap!        <F31> <C-O>dw
   cnoremap        <F31> <S-Right><C-W>
+  tnoremap        <F31> <Esc>d
   noremap!        <F32> <Down>
+  tnoremap        <F32> <Esc>n
   noremap!        <F33> <Up>
+  tnoremap        <F32> <Esc>p
   noremap!        <F34> <C-W>
   noremap!        <F35> <C-W>
   augroup rsi_gui
```
I explain how it works [here](https://github.com/lacygoill/vim-lg-lib/blob/92557e411f682cc20259a371cf526aa460c886c4/import/lg/map.vim#L117-L144).
