### ISSUE TITLE
CTRL-T overrides default mapping in some search modes

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-rsi#47]
`CTRL-T` mapping is currently [explicitly disabled](https://github.com/tpope/vim-rsi/commit/41986218b5094e617bf8c520e878959ad955c9e7) in regular search modes (`/` and `?`) to allow for default behaviour of jumping between `incsearch` results. Recently (I believe) Vim started supporting `/_CTRL-G` and `/_CTRL-T` in other search modes like `:global`, `:vglobal`, and `:substitute`. Previous special casing in `vim-rsi` doesn't work for them so it is impossible to jump back (`/_CTRL-G` works as expected). Can these modes also be special-cased to preserve default `CTRL-T` behaviour?

**Comment by keith** [comment]
See https://github.com/tpope/vim-rsi/pull/40
