### ISSUE TITLE
Ctrl a and Ctrl e when soft wrapping

### ISSUE THREAD

**Issue by emkayonline** [tpope/vim-rsi#50]
Nice plugin. though I have noticed that, for example, C-a moves to the first character in the line, not the first character in the visible line when lines are wrapped.

Would it be possible for the plugin to detect this and use 0 rather than ^ to move to the start of the line? And similar behaviour for C-e, ie using $ for end of line when wrapped.

Thanks

Martin

**Comment by tpope** [comment]
I don't understand the request. Using `0` rather than `^` would still jump to the first character in the line, not the visible line. It would only differ with respect to leading whitespace. And using `$` wouldn't change anything at all.

Please clarify.
