### ISSUE TITLE
You know Readline key bindings?

### ISSUE THREAD

**Issue by ianchanning** [tpope/vim-rsi#52]
Question asked in the README:

> You know Readline key bindings? Of course you do, they're in your shell, your REPL, and perhaps even the GUI for your OS.

Turns out - no I don't, even with a decade of using linux terminals. But this plugin is very helpful through the [doc](https://github.com/tpope/vim-rsi/blob/master/doc/rsi.txt) to show me Readline key bindings that I didn't know existed.

**Comment by tpope** [comment]
cool
