### ISSUE TITLE
a couple missing keybinds?

### ISSUE THREAD

**Issue by nerd190** [tpope/vim-rsi#53]
Hi! thank you for all the great plugins!
I noticed that `sensible.vim` defines two binds:
```vim

if empty(mapcheck('<C-U>', 'i'))
    inoremap <C-U> <C-G>u<C-U>
endif

if empty(mapcheck('<C-W>', 'i'))
    inoremap <C-W> <C-G>u<C-W>
endif

```

These are missing from `rsi.vim`, shouldn't these be added also if `sensible.vim` does not exist?

**Comment by tpope** [comment]
Feels like an orthogonal concern, no? The built-in `<C-W>` already deletes a word as in Readline.
